### ISSUE TITLE
sshkeys join("\n") concatenating with literal \n rather than newline

### ISSUE THREAD

**Issue by mcg** [tschifftner/ansible-role-users#3]
Using Ansible 2.6.4. 

In tasks/ssh.yml, "Configure ~/.ssh/authorized_keys for users". Ends up concatenating a literal "\n" rather than newlines. This is the line in question:

`key: '{{ item.sshkeys | join("\n") }}'` 

Easily fixed by swapping the singe and double quotes as:

`key: "{{ item.sshkeys | join('\n') }}"`

**Comment by mcg** [comment]
Looks like the issue tracker isn't used here.

**Comment by sa-** [comment]
Did you ever figure this out?

**Comment by jippi** [comment]
_screaming in years later with same problem_

**Comment by mberkowski** [comment]
@jippi You have this problem even with the flipped quoting as in the referenced commit? We have a totally different user management role where an Ansible Tower user just reported literal `\n` in authorized_keys and I was hoping to invert the quotes.
